# Generated by Django 2.1.7 on 2019-04-01 07:53

from django.db import migrations


def create_currencies(apps, schema_editor):
    Currency = apps.get_model('common', 'Currency')

    Currency.objects.create(
        code='USD',
        name='US dollar',
    )
    Currency.objects.create(
        code='SEK',
        name='Svensk krona',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_currencies)
    ]
