# Generated by Django 2.1.7 on 2019-04-01 07:53

import uuid

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models

import django_countries.fields
import gan.apps.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('org_number', models.CharField(blank=True, max_length=25, verbose_name='organization no.')),
                ('vat_id', models.CharField(blank=True, max_length=25, verbose_name='VAT id')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='phone')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('address_1', models.CharField(blank=True, max_length=60, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=60, verbose_name='address 2')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='city')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='zip-code')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='state')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('email', gan.apps.common.fields.CustomEmailField(blank=True, max_length=254, verbose_name='email')),
                ('extra_email', gan.apps.common.fields.CustomEmailField(blank=True, max_length=254, verbose_name='extra email')),
                ('extra_phone', models.CharField(blank=True, max_length=25, verbose_name='extra phone')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('different_billing_address', models.BooleanField(default=False, verbose_name='different billing address')),
                ('invoice_email', gan.apps.common.fields.CustomEmailField(max_length=254, verbose_name='invoice email')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.Address')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Currency')),
                ('invoice_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
